### ISSUE TITLE
请问能否提供编译内核的.config文件

### ISSUE THREAD

**Issue by Zxilly** [UJX6N/bbrplus-5.15#1]

**Comment by UJX6N** [comment]
在 **Releases** 页签下载内核安装包或源码包，解开就有config了。

以Centos 7.x为例，下载 **Releases** 里最新版本的内核安装包：

`CentOS-7_Required_kernel-bbrplus-5.15.12-1.bbrplus.el7.x86_64.rpm
`

把它当压缩文件解开

`rpm2cpio CentOS-7_Required_kernel-bbrplus-5.15.12-1.bbrplus.el7.x86_64.rpm | cpio -div`

然后有个boot目录，里面有个文件叫

`config-5.15.12-1.bbrplus.el7.x86_64`

这个就是config文件，把它copy为 **.config** 就可以

**Comment by Zxilly** [comment]
好的，谢谢
